FROM node:10

ENV NODE_VERSION=12.8.1

WORKDIR /srv/app/

COPY webapp/public /srv/app/public
COPY webapp/src /srv/app/src
COPY webapp/package.json webapp/.env /srv/app/

RUN npm install

CMD ["npm", "start"]
