version: '3'
services:
  backend:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - "5000:5000"
  frontend:
    build:
      context: './webapp'
      dockerfile: 'Dockerfile'
    ports: 
      - "3000:3000"
    depends_on:
      - backend
